### ISSUE TITLE
Multipul Woocommerce pages

### ISSUE THREAD

**Issue by Muneera-Salah** [gdarko/Woocommerce-Polylang-Integration#1]
Hi , good plugin But ;
I think there is problem when I test all page store , just show pages selected in woocommerce setting not in two language especially with main page store , How can I solve it ?
Thanks ?

**Comment by gdarko** [comment]
Hello,

Did you followed the instructions?
https://github.com/gdarko/Woocommerce-Polylang-Integration#how-to-use

You should translate the pages in the pages dashboard by clickling 'plus' icon on each page that you want translated.

This plugin is a bridge between woocommerce and polylang. It makes the translated pages with polylang available as official woocommerce pages, like checkout, product, cart and others woocommerce pages to be supported by polylang in non-native language!

**Comment by Muneera-Salah** [comment]
Thank Mr darko
yes I did that , and work very well ,But My Question For example I buy something for Arabic store then go to the cart or checkout page , it move me to English cart or checkout page , yes It work when I go to menu switcher , but I think maybe make hard for customer go and back to menu to change language !


also when I go to woocommerce setting and selected Arabic store page then go to selected English store page then I go back to see Arabic store page it was empty ! no page selected ?

I hope understanding my question and I'm sorry for long .

**Comment by stefanvelickovic33** [comment]
Hi,
What was the solution for this in the end?
